buildscript {
    repositories {
        google()
        mavenCentral()
        jcenter()
        // Added JitPack in case some dependencies are hosted there
        maven { url "https://jitpack.io" }
    }
    dependencies {
        classpath 'com.android.tools.build:gradle:3.1.2'
    }
}

allprojects {
    repositories {
        google()
        mavenCentral()
        jcenter()
        // Added JitPack so 'com.github.googlesamples:easypermissions' and other JitPack libs resolve
        maven { url "https://jitpack.io" }
    }
}

task clean(type: Delete) {
    delete rootProject.buildDir
}
